const wording = new Object();

wording.ALREADY_TAKEN = 'ALREADY_TAKEN';
wording.ALREADY_VERIFIED = 'ALREADY_VERIFIED';
wording.IS_EMPTY = 'IS_EMPTY';
wording.NOT_ARRAY = 'NOT_ARRAY';
wording.NOT_EMAIL_FORMATTED = 'NOT_EMAIL_FORMATTED';
wording.NOT_FOUND = 'NOT_FOUND';
wording.NOT_IN_CHOICE = 'NOT_IN_CHOICE';
wording.NOT_MEET_REQUIREMENT = 'NOT_MEET_REQUIREMENT';
wording.NOT_STRING = 'NOT_STRING';
wording.ROLE_NOT_ALLOWED = 'ROLE_NOT_ALLOWED';
wording.USER_NEED_EMAIL_VERIFICATION = 'USER_NEED_EMAIL_VERIFICATION';
wording.WRONG_PASSWORD = 'WRONG_PASSWORD';

wording.ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND';
wording.ARTICLE_CATEGORY_NOT_FOUND = 'ARTICLE_CATEGORY_NOT_FOUND';
wording.CODE_NOT_FOUND = 'CODE_NOT_FOUND';
wording.PROGRAM_NOT_FOUND = 'PROGRAM_NOT_FOUND';
wording.PROGRAM_TYPE_NOT_FOUND = 'PROGRAM_TYPE_NOT_FOUND';
wording.TOOL_NOT_FOUND = 'TOOL_NOT_FOUND';
wording.USER_NOT_FOUND = 'USER_NOT_FOUND';

module.exports = wording;